"""Added phone number to OAuthUser

Revision ID: 219b3e02b6b6
Revises: 262ad469531f
Create Date: 2025-03-13 23:03:26.035452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219b3e02b6b6'
down_revision: Union[str, None] = '262ad469531f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_users', 'phone')
    # ### end Alembic commands ###
