"""Added OAuthUser model

Revision ID: 262ad469531f
Revises: 
Create Date: 2025-03-13 22:56:50.228075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262ad469531f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_users_email'), 'oauth_users', ['email'], unique=True)
    op.create_index(op.f('ix_oauth_users_id'), 'oauth_users', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_users_provider'), 'oauth_users', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_users_provider_id'), 'oauth_users', ['provider_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_users_provider_id'), table_name='oauth_users')
    op.drop_index(op.f('ix_oauth_users_provider'), table_name='oauth_users')
    op.drop_index(op.f('ix_oauth_users_id'), table_name='oauth_users')
    op.drop_index(op.f('ix_oauth_users_email'), table_name='oauth_users')
    op.drop_table('oauth_users')
    # ### end Alembic commands ###
